### ISSUE TITLE
Horizontally align banner message with icon

### ISSUE THREAD

**Issue by daniellizik** [tablecheck/tablekit#76] opened 2021-12-21 07:38 UTC
![image](https://user-images.githubusercontent.com/10506366/146890093-01bfb1b4-9697-4c96-b72e-505d445e40d5.png)

**Comment by gazpachu** [comment] 2022-10-18 07:14
Duplicate of #39 . It should be fixed now

**Closed by gazpachu** 2022-10-18 07:14 UTC
Labels: banner
